name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - run: |
          # https://github.com/actions/setup-go/issues/107
          #cp -f `which go` /usr/bin/go
          go version

      - name: Make All
        run: |
          ./package.sh

      - name: Create Tag
        run: |
          version=`./bin/wfrpc --version`
          if ! git tag -l $version; then
            git tag $version
            git push origin $version
          fi
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
